name: fl_pkgtesting
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#---------PACKAGES----------#
dependencies:
  flutter:
    sdk: flutter
  # UI Packages
  carousel_slider: ^5.0.0
  easy_stepper: ^0.8.5+1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0

  # Images Support
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_svg: ^2.1.0

  # Writing Support
  flutter_form_builder: ^10.0.1
  flutter_quill: ^11.4.0

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Internationalization
  easy_localization: ^3.0.7+1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5

  # Local Storage
  shared_preferences: ^2.2.2

  # Connection & HTTP/REST API
  connectivity_plus: ^6.1.4
  http: ^1.3.0
  dio: ^5.8.0+1

  # Utility Packages
  logger: ^2.4.0

  # Other
  super_tooltip: ^2.0.9
  app_settings: ^6.1.1
  bloc: ^9.0.0
#---------PACKAGES - END----------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logos/logo_main.png

flutter:
  uses-material-design: true

#--------LOCAL ASSETS--------------#
assets:
  - assets/
  - assets/gifs/
  - assets/images/
  - assets/gifs/
  #--------LOCAL FONTS---------------#
  - assets/fonts/
